# Generated by Django 4.2.16 on 2024-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_store', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
